relative_permalinks: false

url: http://test2.html9.com

title: 全能保险柜官网

permalink: /:categories/:title.html

image_cdn: http://www.qnnsafe.com

prodimgs: http://images.qnnsafe.com

markdown: rdiscount

exclude: ['README.md','LICENSE']
